### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jmpas** [lyef/lyef-react-cli#8]
Right now we have the `create` command working (at least the MVP of it).
I was thinking about releasing it, but maybe we should do somethings before, that may be important to have.

What I've in mind:

- [ ] [Create specs](https://github.com/lyef/lyef-react-cli/issues/7)
- [ ] [Improve streams and error handling](https://github.com/lyef/lyef-react-cli/issues/4)
- [ ] At least one more CLI command
- [ ] CI
- [ ] Add speed benchmarking comparing with other CLIs / generators (would be cool to know)
- [ ] A GIF using it (because it's cool :trollface:)

I'll try to start working on them, but I wanted to open this issue for us and anyone that wants to contribute be able to talk about the first release.
